In [4]:
# Solution on Data Preprocessing Exercise
# 1. Deliberately change the value of data to missing value in each feature of the dataset

import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer, KNNImputer

# Load the dataset
data11 = pd.read_csv('dataset/iris.csv')

iris_df = data11.iloc[:, :-1]

np.random.seed(42)  

for col in iris_df.columns:
    missing_indices = np.random.choice(iris_df.index, size=10, replace=False)
    iris_df.loc[missing_indices, col] = np.nan

print("DataFrame with missing values:")
print(iris_df)





DataFrame with missing values:
     5.1  3.5  1.4  0.2
0    4.9  3.0  1.4  0.2
1    4.7  3.2  1.3  0.2
2    4.6  3.1  1.5  0.2
3    5.0  3.6  1.4  0.2
4    5.4  3.9  1.7  0.4
..   ...  ...  ...  ...
144  6.7  3.0  5.2  NaN
145  6.3  2.5  5.0  1.9
146  6.5  3.0  5.2  2.0
147  6.2  3.4  5.4  2.3
148  5.9  3.0  5.1  1.8

[149 rows x 4 columns]


In [ ]:

                    # 2.Impute the missing value data with mean value of the corresponding feature value

import pandas as pd

print("\nMissing values before imputation:")
print(iris_df.isnull().sum())

# Instead of using inplace=True
for col in iris_df.select_dtypes(include=['number']).columns:
    mean_value = iris_df[col].mean()
    iris_df[col] = iris_df[col].fillna(mean_value)   

print("\nDataFrame after mean imputation (numeric columns only):")
print(iris_df.head())
print("\nMissing values after imputation:")
print(iris_df.isnull().sum())

# Step 2: Assign Class column from data11
iris_df['Class'] = data11.iloc[:, 4]  # 5th column from data11

print("\nDataFrame after adding 'Class' column:")
print(iris_df.head())


Missing values before imputation:
5.1    10
3.5    10
1.4    10
0.2    10
dtype: int64

DataFrame after mean imputation (numeric columns only):
   5.1  3.5  1.4  0.2
0  4.9  3.0  1.4  0.2
1  4.7  3.2  1.3  0.2
2  4.6  3.1  1.5  0.2
3  5.0  3.6  1.4  0.2
4  5.4  3.9  1.7  0.4

Missing values after imputation:
5.1    0
3.5    0
1.4    0
0.2    0
dtype: int64

DataFrame after adding 'Class' column:
   5.1  3.5  1.4  0.2        Class
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa


In [ ]:
                      # 3.Adjust the precision to 2 round off. 

# code to round ofto 3 decimal place
iris_df=iris_df.round(3)
print(iris_df)
data=np.concatenate((iris_df,data11),axis=1)
print(data)

     5.1  3.5  1.4    0.2           Class
0    4.9  3.0  1.4  0.200     Iris-setosa
1    4.7  3.2  1.3  0.200     Iris-setosa
2    4.6  3.1  1.5  0.200     Iris-setosa
3    5.0  3.6  1.4  0.200     Iris-setosa
4    5.4  3.9  1.7  0.400     Iris-setosa
..   ...  ...  ...    ...             ...
144  6.7  3.0  5.2  1.196  Iris-virginica
145  6.3  2.5  5.0  1.900  Iris-virginica
146  6.5  3.0  5.2  2.000  Iris-virginica
147  6.2  3.4  5.4  2.300  Iris-virginica
148  5.9  3.0  5.1  1.800  Iris-virginica

[149 rows x 5 columns]
[[4.9 3.0 1.4 ... 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.3 ... 1.3 0.2 'Iris-setosa']
 [4.6 3.1 1.5 ... 1.5 0.2 'Iris-setosa']
 ...
 [6.5 3.0 5.2 ... 5.2 2.0 'Iris-virginica']
 [6.2 3.4 5.4 ... 5.4 2.3 'Iris-virginica']
 [5.9 3.0 5.1 ... 5.1 1.8 'Iris-virginica']]


In [ ]:

# 4.Impute the missing value data with most frequent value of the corresponding feature

from sklearn.impute import SimpleImputer  

data2 = pd.read_csv('dataset/irisMissingValue.csv')

# Check last few rows and missing values
print(data2.tail())
print(round(data2.isnull().sum(), 2).sort_values(ascending=False))

# Impute missing values with most frequent value
imp_mode = SimpleImputer(strategy='most_frequent')  
data2_imputed = imp_mode.fit_transform(data2)       

# Convert back to DataFrame to keep column names
data2_imputed = pd.DataFrame(data2_imputed, columns=data2.columns)

print("\nData after imputing most frequent value:\n")
print(data2_imputed.tail())

     5.1  3.5  1.4  0.2     Iris-setosa
144  6.7  3.0  5.2  NaN  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica
5.1            10
3.5            10
1.4            10
0.2            10
Iris-setosa     0
dtype: int64

Data after imputing most frequent value:

     5.1  3.5  1.4  0.2     Iris-setosa
144  6.7  3.0  5.2  0.2  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica


In [8]:
#             5.Impute the missing value data with a constant value 100 to every corresponding feature

#  Imputation with constant vales
data2 = pd.read_csv('dataset/irisMissingValue.csv')
print (data2.tail())
print (round(data2.isnull().sum(), 2).sort_values(ascending=False))
imputer = SimpleImputer(strategy='constant', fill_value=100)
imp_cons=imputer
imp_cons.fit(data2)
data2=imp_cons.transform(data2)
print (data2)

     5.1  3.5  1.4  0.2     Iris-setosa
144  6.7  3.0  5.2  NaN  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica
5.1            10
3.5            10
1.4            10
0.2            10
Iris-setosa     0
dtype: int64
[[4.9 3.0 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.3 0.2 'Iris-setosa']
 [4.6 3.1 1.5 0.2 'Iris-setosa']
 [5.0 3.6 1.4 0.2 'Iris-setosa']
 [5.4 3.9 1.7 0.4 'Iris-setosa']
 [4.6 3.4 1.4 100 'Iris-setosa']
 [5.0 3.4 1.5 0.2 'Iris-setosa']
 [4.4 2.9 1.4 0.2 'Iris-setosa']
 [4.9 3.1 1.5 0.1 'Iris-setosa']
 [5.4 100 1.5 0.2 'Iris-setosa']
 [4.8 3.4 100 0.2 'Iris-setosa']
 [4.8 3.0 1.4 0.1 'Iris-setosa']
 [4.3 3.0 1.1 0.1 'Iris-setosa']
 [5.8 4.0 1.2 0.2 'Iris-setosa']
 [5.7 100 1.5 100 'Iris-setosa']
 [5.4 3.9 1.3 0.4 'Iris-setosa']
 [5.1 3.5 1.4 0.3 'Iris-setosa']
 [5.7 3.8 1.7 100 'Iris-setosa']
 [100 3.8 1.5 0.3 'Iris-setosa']
 [5.4 3.4 1.7 0.2 'Iris-setosa

In [ ]:
               # 6.Impute the missing value data with KNN where N=2


data2 = pd.read_csv('dataset/irisMissingValue.csv')

# Remove class column (keep only features)
Before_imputation = data2.iloc[:, :-1]

# Show data before imputation
print("Data Before performing imputation:\n", Before_imputation)

# Create KNN Imputer (K = 2)
imputer = KNNImputer(n_neighbors=2)

# Apply imputation
# fit()
# Learns the structure of the dataset
# Computes distances between rows
# transform()
# Replaces missing values (NaN) using:
# → average of the 2 nearest neighbors
After_imputation = imputer.fit_transform(Before_imputation)

# Convert back to DataFrame
After_imputation = pd.DataFrame(
    After_imputation,
    columns=Before_imputation.columns
)

# Show result
print("\nAfter performing imputation:\n", After_imputation)

Data Before performing imputation:
      5.1  3.5  1.4  0.2
0    4.9  3.0  1.4  0.2
1    4.7  3.2  1.3  0.2
2    4.6  3.1  1.5  0.2
3    5.0  3.6  1.4  0.2
4    5.4  3.9  1.7  0.4
..   ...  ...  ...  ...
144  6.7  3.0  5.2  NaN
145  6.3  2.5  5.0  1.9
146  6.5  3.0  5.2  2.0
147  6.2  3.4  5.4  2.3
148  5.9  3.0  5.1  1.8

[149 rows x 4 columns]

After performing imputation:
      5.1  3.5  1.4   0.2
0    4.9  3.0  1.4  0.20
1    4.7  3.2  1.3  0.20
2    4.6  3.1  1.5  0.20
3    5.0  3.6  1.4  0.20
4    5.4  3.9  1.7  0.40
..   ...  ...  ...   ...
144  6.7  3.0  5.2  2.15
145  6.3  2.5  5.0  1.90
146  6.5  3.0  5.2  2.00
147  6.2  3.4  5.4  2.30
148  5.9  3.0  5.1  1.80

[149 rows x 4 columns]


In [ ]:
# 7.delete records of dataset with missing values 

data2 = pd.read_csv('dataset/irisMissingValue.csv')

# drop last column (correct pandas way)
data2 = data2.iloc[:, :-1]

print(len(data2))

data2 = data2.dropna()

print(data2.isnull().sum())
print(data2)

149
5.1    0
3.5    0
1.4    0
0.2    0
dtype: int64
     5.1  3.5  1.4  0.2
0    4.9  3.0  1.4  0.2
1    4.7  3.2  1.3  0.2
2    4.6  3.1  1.5  0.2
3    5.0  3.6  1.4  0.2
4    5.4  3.9  1.7  0.4
..   ...  ...  ...  ...
143  6.7  3.3  5.7  2.5
145  6.3  2.5  5.0  1.9
146  6.5  3.0  5.2  2.0
147  6.2  3.4  5.4  2.3
148  5.9  3.0  5.1  1.8

[114 rows x 4 columns]


In [1]:


#           8.Transform the dataset to Min-Max Normalization

import math as m
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
data=pd.read_csv('dataset/iris.csv',header=None)
data2= (data.iloc[:,:-1])
print (data2.head())
print (data2.shape)
Scaler=MinMaxScaler()
ScaledData=Scaler.fit_transform (data2)
ScaledData=ScaledData.round(2)
print (ScaledData)
print (ScaledData.shape)

     0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2
(150, 4)
[[0.22 0.62 0.07 0.04]
 [0.17 0.42 0.07 0.04]
 [0.11 0.5  0.05 0.04]
 [0.08 0.46 0.08 0.04]
 [0.19 0.67 0.07 0.04]
 [0.31 0.79 0.12 0.12]
 [0.08 0.58 0.07 0.08]
 [0.19 0.58 0.08 0.04]
 [0.03 0.38 0.07 0.04]
 [0.17 0.46 0.08 0.  ]
 [0.31 0.71 0.08 0.04]
 [0.14 0.58 0.1  0.04]
 [0.14 0.42 0.07 0.  ]
 [0.   0.42 0.02 0.  ]
 [0.42 0.83 0.03 0.04]
 [0.39 1.   0.08 0.12]
 [0.31 0.79 0.05 0.12]
 [0.22 0.62 0.07 0.08]
 [0.39 0.75 0.12 0.08]
 [0.22 0.75 0.08 0.08]
 [0.31 0.58 0.12 0.04]
 [0.22 0.71 0.08 0.12]
 [0.08 0.67 0.   0.04]
 [0.22 0.54 0.12 0.17]
 [0.14 0.58 0.15 0.04]
 [0.19 0.42 0.1  0.04]
 [0.19 0.58 0.1  0.12]
 [0.25 0.62 0.08 0.04]
 [0.25 0.58 0.07 0.04]
 [0.11 0.5  0.1  0.04]
 [0.14 0.46 0.1  0.04]
 [0.31 0.58 0.08 0.12]
 [0.25 0.87 0.08 0.  ]
 [0.33 0.92 0.07 0.04]
 [0.17 0.46 0.08 0.  ]
 [0.19 0.5  0.03 0.04]
 [0.33 0.62 0.05 0.04]
 [0.17 0

In [2]:

                   # 9.Transform the dataset to Z-Score Normalization

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
data=pd.read_csv('dataset/iris.csv',header=None)
data2= (data.iloc[:,:-1])
normalized_data = scaler.fit_transform(data2)
print("Original data:\n \n \n", data2) # Flatten to print as 1D
print("Z-score normalized data (sklearn): \n \n \n", normalized_data)

Original data:
 
 
        0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]
Z-score normalized data (sklearn): 
 
 
 [[-9.00681170e-01  1.03205722e+00 -1.34127240e+00 -1.31297673e+00]
 [-1.14301691e+00 -1.24957601e-01 -1.34127240e+00 -1.31297673e+00]
 [-1.38535265e+00  3.37848329e-01 -1.39813811e+00 -1.31297673e+00]
 [-1.50652052e+00  1.06445364e-01 -1.28440670e+00 -1.31297673e+00]
 [-1.02184904e+00  1.26346019e+00 -1.34127240e+00 -1.31297673e+00]
 [-5.37177559e-01  1.95766909e+00 -1.17067529e+00 -1.05003079e+00]
 [-1.50652052e+00  8.00654259e-01 -1.34127240e+00 -1.18150376e+00]
 [-1.02184904e+00  8.00654259e-01 -1.28440670e+00 -1.31297673e+00]
 [-1.74885626e+00 -3.56360566e-01 -1.34127240e+00 -1.31297673e+00]
 [-1.14301691e+00  1.064

In [15]:
            

    # 10.Take the age of patient from the hospital as follows 

import pandas as pd
import numpy as np
data=pd.read_csv('dataset/data8.csv')
print("Before: ")
print(data)
Label = pd.cut(x=data['Age'], bins=[0, 3, 7, 17, 63, 99],
labels=['Baby', 'Child', 'Teenage', 'Adult', 'Elderly'])
print("After: \n ", Label)
print("Categories: ")
print(Label.value_counts())
data = pd.concat([data, Label], axis=1)
print ("\n \n \n Merged Data \n \n", data)

Before: 
    Age
0    42
1    15
2    67
3    55
4     1
5    29
6    75
7    89
8     4
9    10
10   15
11   38
12   22
13   77
After: 
  0       Adult
1     Teenage
2     Elderly
3       Adult
4        Baby
5       Adult
6     Elderly
7     Elderly
8       Child
9     Teenage
10    Teenage
11      Adult
12      Adult
13    Elderly
Name: Age, dtype: category
Categories (5, str): ['Baby' < 'Child' < 'Teenage' < 'Adult' < 'Elderly']
Categories: 
Age
Adult      5
Elderly    4
Teenage    3
Baby       1
Child      1
Name: count, dtype: int64

 
 
 Merged Data 
 
     Age      Age
0    42    Adult
1    15  Teenage
2    67  Elderly
3    55    Adult
4     1     Baby
5    29    Adult
6    75  Elderly
7    89  Elderly
8     4    Child
9    10  Teenage
10   15  Teenage
11   38    Adult
12   22    Adult
13   77  Elderly


In [16]:


                    # 11 Consider the following dataset and apply one hot encoding to the feature ‘city

import pandas as pd

# Read the dataset
data = pd.read_csv('dataset/city_data.csv')
print("Original Data:\n", data)

# Apply one-hot encoding to the 'city' column
data_encoded = pd.get_dummies(data, columns=['city'])

print("\nData after one-hot encoding:\n", data_encoded)

Original Data:
         city  area   price
0   Hawasssa   260  550000
1   Hawasssa   300  565000
2   Hawasssa   320  610000
3   Hawasssa   360  680000
4   Hawasssa   400  725000
5      Adama   260  585000
6      Adama   280  615000
7      Adama   330  650000
8      Adama   360  710000
9   BahirDar   260  575000
10  BahirDar   290  600000
11  BahirDar   310  620000
12  BahirDar   360  695000

Data after one-hot encoding:
     area   price  city_Adama  city_BahirDar  city_Hawasssa
0    260  550000       False          False           True
1    300  565000       False          False           True
2    320  610000       False          False           True
3    360  680000       False          False           True
4    400  725000       False          False           True
5    260  585000        True          False          False
6    280  615000        True          False          False
7    330  650000        True          False          False
8    360  710000        True          False 